USE [master]
GO
/****** Object:  Database [DBPROYECTOCARRITO]    Script Date: 18/07/2024 19:33:18 ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'DBPROYECTOCARRITO')
BEGIN
CREATE DATABASE [DBPROYECTOCARRITO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBPROYECTOCARRITO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DBPROYECTOCARRITO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBPROYECTOCARRITO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\DBPROYECTOCARRITO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
END
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBPROYECTOCARRITO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET  MULTI_USER 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET QUERY_STORE = OFF
GO
USE [DBPROYECTOCARRITO]
GO
/****** Object:  Table [dbo].[CARRITO]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CARRITO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CARRITO](
	[IdCarrito] [int] IDENTITY(1,1) NOT NULL,
	[IdCliente] [int] NULL,
	[IdProducto] [int] NULL,
	[Cantidad] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdCarrito] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[CATEGORIA]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CATEGORIA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CATEGORIA](
	[IdCategoria] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](100) NULL,
	[Activo] [bit] NULL,
	[FechaRegistro] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdCategoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLIENTE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CLIENTE](
	[IdCliente] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NULL,
	[Apellido] [varchar](100) NULL,
	[Correo] [varchar](100) NULL,
	[Clave] [varchar](150) NULL,
	[Restablecer] [bit] NULL,
	[FechaRegistro] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[DETALLE_VENTA]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DETALLE_VENTA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DETALLE_VENTA](
	[IdDetalleVenta] [int] IDENTITY(1,1) NOT NULL,
	[IdVenta] [int] NULL,
	[IdProducto] [int] NULL,
	[Cantidad] [int] NULL,
	[Total] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[IdDetalleVenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[DISTRITO]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DISTRITO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DISTRITO](
	[IdDistrito] [varchar](3) NOT NULL,
	[Descripcion] [varchar](50) NOT NULL,
	[IdMunicipio] [varchar](3) NOT NULL,
	[IdProvincia] [varchar](2) NOT NULL
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[MARCA]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MARCA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[MARCA](
	[IdMarca] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](100) NULL,
	[Activo] [bit] NULL,
	[FechaRegistro] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdMarca] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[MUNICIPIO]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MUNICIPIO]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[MUNICIPIO](
	[IdMunicipio] [varchar](3) NOT NULL,
	[Descripcion] [varchar](50) NOT NULL,
	[IdProvincia] [varchar](2) NOT NULL
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Producto]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Producto](
	[IdProducto] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](500) NULL,
	[Descripcion] [varchar](500) NULL,
	[IdMarca] [int] NULL,
	[IdCategoria] [int] NULL,
	[Precio] [decimal](10, 2) NULL,
	[Stock] [int] NULL,
	[RutaImagen] [varchar](100) NULL,
	[NombreImagen] [varchar](100) NULL,
	[Activo] [bit] NULL,
	[FechaRegistro] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[PROVINCIA]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROVINCIA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PROVINCIA](
	[IdProvincia] [varchar](2) NOT NULL,
	[Descripcion] [varchar](50) NOT NULL
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[USUARIOS]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USUARIOS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[USUARIOS](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NULL,
	[Apellido] [varchar](100) NULL,
	[Correo] [varchar](100) NULL,
	[Clave] [varchar](150) NULL,
	[Restablecer] [bit] NULL,
	[Activo] [bit] NULL,
	[FechaRegistro] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[VENTA]    Script Date: 18/07/2024 19:33:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VENTA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[VENTA](
	[IdVenta] [int] IDENTITY(1,1) NOT NULL,
	[IdCliente] [int] NULL,
	[TotalProducto] [int] NULL,
	[MontoTotal] [decimal](10, 2) NULL,
	[Contacto] [varchar](50) NULL,
	[IdProvincia] [varchar](20) NULL,
	[Telefono] [varchar](50) NULL,
	[Direccion] [varchar](100) NULL,
	[IdTransaccion] [varchar](50) NULL,
	[FechaVenta] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdVenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CATEGORIA__Activ__37A5467C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CATEGORIA] ADD  DEFAULT ((1)) FOR [Activo]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CATEGORIA__Fecha__38996AB5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CATEGORIA] ADD  DEFAULT (getdate()) FOR [FechaRegistro]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CLIENTE__Restabl__45F365D3]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CLIENTE] ADD  DEFAULT ((0)) FOR [Restablecer]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__CLIENTE__FechaRe__46E78A0C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[CLIENTE] ADD  DEFAULT (getdate()) FOR [FechaRegistro]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__MARCA__Activo__3B75D760]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[MARCA] ADD  DEFAULT ((1)) FOR [Activo]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__MARCA__FechaRegi__3C69FB99]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[MARCA] ADD  DEFAULT (getdate()) FOR [FechaRegistro]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Producto__Precio__412EB0B6]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Producto] ADD  DEFAULT ((0)) FOR [Precio]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Producto__Activo__4222D4EF]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Producto] ADD  DEFAULT ((1)) FOR [Activo]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Producto__FechaR__4316F928]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Producto] ADD  DEFAULT (getdate()) FOR [FechaRegistro]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__USUARIOS__Restab__5535A963]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[USUARIOS] ADD  DEFAULT ((0)) FOR [Restablecer]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__USUARIOS__Activo__5629CD9C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[USUARIOS] ADD  DEFAULT ((1)) FOR [Activo]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__USUARIOS__FechaR__571DF1D5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[USUARIOS] ADD  DEFAULT (getdate()) FOR [FechaRegistro]
END
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__VENTA__FechaVent__4E88ABD4]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[VENTA] ADD  DEFAULT (getdate()) FOR [FechaVenta]
END
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__CARRITO__IdClien__49C3F6B7]') AND parent_object_id = OBJECT_ID(N'[dbo].[CARRITO]'))
ALTER TABLE [dbo].[CARRITO]  WITH CHECK ADD FOREIGN KEY([IdCliente])
REFERENCES [dbo].[CLIENTE] ([IdCliente])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__CARRITO__IdProdu__4AB81AF0]') AND parent_object_id = OBJECT_ID(N'[dbo].[CARRITO]'))
ALTER TABLE [dbo].[CARRITO]  WITH CHECK ADD FOREIGN KEY([IdProducto])
REFERENCES [dbo].[Producto] ([IdProducto])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__DETALLE_V__IdPro__52593CB8]') AND parent_object_id = OBJECT_ID(N'[dbo].[DETALLE_VENTA]'))
ALTER TABLE [dbo].[DETALLE_VENTA]  WITH CHECK ADD FOREIGN KEY([IdProducto])
REFERENCES [dbo].[Producto] ([IdProducto])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__DETALLE_V__IdVen__5165187F]') AND parent_object_id = OBJECT_ID(N'[dbo].[DETALLE_VENTA]'))
ALTER TABLE [dbo].[DETALLE_VENTA]  WITH CHECK ADD FOREIGN KEY([IdVenta])
REFERENCES [dbo].[VENTA] ([IdVenta])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__Producto__IdCate__403A8C7D]') AND parent_object_id = OBJECT_ID(N'[dbo].[Producto]'))
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD FOREIGN KEY([IdCategoria])
REFERENCES [dbo].[CATEGORIA] ([IdCategoria])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__Producto__IdMarc__3F466844]') AND parent_object_id = OBJECT_ID(N'[dbo].[Producto]'))
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD FOREIGN KEY([IdMarca])
REFERENCES [dbo].[MARCA] ([IdMarca])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__VENTA__IdCliente__4D94879B]') AND parent_object_id = OBJECT_ID(N'[dbo].[VENTA]'))
ALTER TABLE [dbo].[VENTA]  WITH CHECK ADD FOREIGN KEY([IdCliente])
REFERENCES [dbo].[CLIENTE] ([IdCliente])
GO
USE [master]
GO
ALTER DATABASE [DBPROYECTOCARRITO] SET  READ_WRITE 
GO
